extends: _base.yaml
experiment_b:
  mode: precomputed_aug
  precomputed_dataset_dir: artifacts/generated/yolo/exp_b/precomputed_candidates/regiondiff_fm_ot_hflip
  augmented_yolo_root: artifacts/generated/yolo/exp_b/flir_yolov8m/augmented_yolo
  disable_ultralytics_augmentations: false
  filter:
    enabled: false
output:
  experiment_name: exp_precomputed_regiondiff_fm_ot_hflip
