extends: _base.yaml
experiment_b:
  mode: fm_aug
  invalid_instance_ratio_threshold: 0.6
  generated_dataset_dir: artifacts/generated/yolo/exp_b/flir_yolov8m/generated_candidates
  augmented_yolo_root: artifacts/generated/yolo/exp_b/flir_yolov8m/augmented_yolo
  disable_ultralytics_augmentations: false
  filter:
    checkpoint_dir: artifacts/checkpoints/multiclass_foreground_background_filter/runs/multiclass_fgbg_20260415_210440/checkpoints
    batch_size: 64
  fm:
    checkpoint_path: artifacts/checkpoints/flow_matching/serious_runs/stay_layout_latent_flir_sd15_512/UNET/unet_fm_epoch_270.pt
    preset_path: configs/fm/train/presets/stay_layout_latent_flir_sd15_512.yaml
    steps: 20
    batch_size: 8
output:
  experiment_name: exp_fm_aug
