extends: _base.yaml
experiment_b:
  mode: precomputed_aug
  precomputed_dataset_dir: artifacts/generated/yolo/exp_b/precomputed_candidates/stay_fm_hflip
  augmented_yolo_root: artifacts/generated/yolo/exp_b/flir_yolov8n/augmented_yolo
  disable_ultralytics_augmentations: true
  filter:
    enabled: false
output:
  experiment_name: exp_precomputed_stay_fm_hflip
