extends: _base.yaml
experiment_b:
  mode: sd_aug
  invalid_instance_ratio_threshold: 0.5
  generated_dataset_dir: artifacts/generated/yolo/exp_b/flir_yolov8n/generated_candidates
  augmented_yolo_root: artifacts/generated/yolo/exp_b/flir_yolov8n/augmented_yolo
  disable_ultralytics_augmentations: true
  filter:
    checkpoint_dir: artifacts/checkpoints/multiclass_foreground_background_filter/runs/multiclass_fgbg_20260415_210440/checkpoints
    batch_size: 64
  sd:
    lora_dir: artifacts/checkpoints/stable_diffusion/lora_runs/flir_sd15_lora_stage1_r128
    base_model: runwayml/stable-diffusion-v1-5
    sd_steps: 100
    guidance: 7.5
    precision: fp16
    max_tries: 25
    prompt_mode: constant
output:
  experiment_name: exp_sd_aug_lora
