generated_dataset_dir: ""
filter_run_dir: ""
filter_checkpoint: ""
max_discarded_valid_threshold: 1.0
score_alpha: 1.0
score_beta: 1.0
min_valid_object_fraction_sweep: ""
batch_size: 64
device: cuda:0
